name: 'Linting'
on: [ push, pull_request ]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  Linting:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ADMIN_PAT || github.token }}

      # Install Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      # Install Ruff
      - name: Install Ruff
        run: sudo snap install ruff

      # Run Ruff linter
      - name: Run Ruff format
        run: ruff format && ruff check . --fix
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'fix: Linting and formatting via Ruff'
