on:
  workflow_dispatch:
    inputs:
        KEEP_AMOUNT:
            description: "Number of images to keep"
            required: true
            default: "10"
        REMOVE_UNTAGGED:
            description: "Remove untagged images"
            required: true
            default: "false"

jobs:
  remove-old-images:
    runs-on: ubuntu-latest

    steps:
      - name: Remove old images
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'tux'
          package-type: 'container'
          min-versions-to-keep: ${{ github.event.inputs.KEEP_AMOUNT }}
          delete-only-untagged-versions: ${{ github.event.inputs.REMOVE_UNTAGGED }}
